language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
env:
    - DJANGO="django==1.8.18"
    - DJANGO="django==1.9.13"
    - DJANGO="django==1.10.8"
    - DJANGO="django==1.11.9"
    - DJANGO="django==2.0.6"
matrix:
  exclude:
   - python: "2.7"
     env: DJANGO="django==2.0.6"
install:
    - pip install Pillow
    - pip install $DJANGO
    - pip install django-formtools>=1.0
    - pip install django-nose
    - pip install coveralls
script:
    - coverage run --source=db_file_storage demo_and_tests/manage.py test
after_success:
    - coveralls
