language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
env:
    - DJANGO="django>=1.8,<1.9"
    - DJANGO="django>=1.9,<1.10"
    - DJANGO="django>=1.10,<1.11"
    - DJANGO="django>=1.11,<2.0"
    - DJANGO="django>=2.0,<2.1"
install:
    - pip install Pillow
    - pip install $DJANGO
    - pip install django-formtools>=1.0
    - pip install django-nose
    - pip install coveralls
script:
    - coverage run --source=db_file_storage demo_and_tests/manage.py test
after_success:
    - coveralls
